// format -- xyz, x - 1. stake, 2. LendingBorrowing, y - 0. eth chain, 1 near, z- protocolId
export enum Adapters
{
    NONE = "none",
    DEFAULT = "default",
    STADERSTAKE = "stader_stake",
    BENQISTAKE = "benqi_stake",
    LIDOSTAKE = "lido_stake",
    METAPOOLSTAKE = "metapool_stake",
    SWELLSTAKE = "swell_stake",
    DEXSPANSWAP = "dex_swap",
    FORWARDERBRIDGE = "nitro_bridge",
    STADERUNSTAKE = "stader_unstake",
    STADERCLAIM = "stader_claim",
    AERODROMEDEPOSIT = "aerodrome_deposit",
    PARIFIDEPOSIT = "parifi_deposit",
    VELOCOREDEPOSIT = "velocore_deposit",
    LIDO_CANONICAL_BRIDGE = "lido_canonical_bridge",
    STAKESTONE_STAKE = "stakestone_stake",
    STAKESTONE_CANONICAL_BRIDGE = "stakestone_canonical_bridge",
    VELOCORESTAKE = "velocore_stake",
    PARIFIOPENPOSITION = "parifi_openPosition",
    KIMDEPOSITV4 = "kim_deposit_v4",
    KIMDEPOSITV2 = "kim_deposit_v2",
    SWAPMODEDEPOSITV3 = "swapmode_deposit_v3",
    SWAPMODEDEPOSITV2 = "swapmode_deposit_v2",
    BASESWAPDEPOSITV3 = "baseswap_deposit",
    LYNEXDEPOSITV2 = "lynex_deposit",
    THRUSTERDEPOSITV2 = "thruster_deposit_v2",
    THRUSTERDEPOSITV3 = "thruster_deposit_v3",
    THIRDFYDEPOSIT = "thirdfy_deposit",
    ASSETBRIDGE = "asset_bridge",
    THIRDFYSWAP = "thirdfy_swap",
    LYNEXSTAKE = "lynex_stake"
}
